# Generated by Django 2.2 on 2020-09-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_jsndv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsndv',
        ),
    ]
